version: '3.8'

services:

  postgres:
    image: postgres
    container_name: postgres_revoada_server
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
    ports:
      - ${DB_PORT}:5432
    networks:
      - local-keycloak

  keycloak:
    container_name: keycloak_revoada_server
    image: jboss/keycloak
    restart: unless-stopped
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: ${KEYCLOACK_DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASS}
      DB_SCHEMA: public
      KEYCLOAK_FRONTEND_URL: http://localhost:${KEYCLOACK_PORT}/auth
    ports:
      - ${KEYCLOACK_PORT}:8080
    networks:
      - local-keycloak
    depends_on:
      postgres:
        condition: service_started

networks:
  local-keycloak:
    driver: bridge
